Repository TEAM-SEONYAK/SEONYAK-SERVER, pull requests merged in 2024-10, with the labels that each got.

#147 [FIX] #146 - 회원가입 시 휴대전화 번호 저장 형식 수정
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
Labels: 🛠️ FIX, ⚰️ DEL, 🐈‍⬛ 창균

#149 [FIX] #148 - 약속 신청/수락/거절 문자 발송 시 문구 오류 수정
  .github/pull_request_template.md
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
Labels: 🛠️ FIX, 📂 FILE, 🐈‍⬛ 창균

#153 [FEAT] #152 - 스웨거 연동
  build.gradle
  src/main/java/org/sopt/seonyakServer/SeonyakServerApplication.java
  src/main/java/org/sopt/seonyakServer/global/auth/security/SecurityConfig.java
  src/main/java/org/sopt/seonyakServer/global/config/SwaggerConfig.java
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
Labels: ✨ FEAT, 🧩 CHORE, 🐯 석범

#154 [FEAT] #150 - 약속 신청 고민 작성/선택 중복 입력, 선택 안함 방지
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT

#156 [REFACTOR] - #155 이미지 업로드 persigned url로 일괄 변경
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Controller.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Service.java
Labels: ♻️ REFACTOR, 🐯 석범

#157 [FIX] #151 - 대학 이메일 인증 방식 변경
  build.gradle
  src/main/java/org/sopt/seonyakServer/domain/university/controller/UnivController.java
  src/main/java/org/sopt/seonyakServer/domain/university/dto/UnivVerifyCodeRequest.java
  src/main/java/org/sopt/seonyakServer/domain/university/dto/UnivVerifyRequest.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/UnivCode.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/UniversityEmail.java
  src/main/java/org/sopt/seonyakServer/domain/university/repository/UnivCodeRepository.java
  src/main/java/org/sopt/seonyakServer/domain/university/repository/UniversityEmailRepository.java
  src/main/java/org/sopt/seonyakServer/domain/university/service/UnivCodeService.java
  src/main/java/org/sopt/seonyakServer/domain/university/service/UnivService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertController.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertClientRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertVerifyClientRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertVerifyRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/FeignErrorDecoder.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/UnivCertClient.java
  src/main/java/org/sopt/seonyakServer/global/config/FeignConfig.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: 🛠️ FIX, 🧩 CHORE, ⚰️ DEL, 🐯 석범
