Repository TEAM-SEONYAK/SEONYAK-SERVER, pull requests merged in 2024-07, with the labels that each got.

#11 [FEAT] #10 - 소셜 로그인 로직 구현 (구글)
  build.gradle
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/LoginSuccessResponse.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/global/auth/MemberAuthentication.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/CustomAccessDeniedHandler.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/org/sopt/seonyakServer/global/auth/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/seonyakServer/global/auth/jwt/JwtValidationType.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/config/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/domain/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/repository/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/service/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/security/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/security/SecurityConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/SocialType.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/dto/GoogleAccessTokenResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/dto/GoogleUserInfoResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/dto/MemberInfoResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/dto/MemberLoginRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/google/GoogleAccessTokenClient.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/google/GoogleSocialService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/google/GoogleUserClient.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/service/SocialService.java
  src/main/java/org/sopt/seonyakServer/global/config/FeignClientConfig.java
  src/main/java/org/sopt/seonyakServer/global/config/QueryDslConfig.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#12 [FEAT] #10 - 소셜 로그인 로직 구현 코드 리뷰 반영 및 추가 구현 사항
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/SocialType.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberManagementService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/CustomAccessDeniedHandler.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/CustomJwtAuthenticationEntryPoint.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/org/sopt/seonyakServer/global/auth/jwt/JwtTokenProvider.java
  src/main/java/org/sopt/seonyakServer/global/auth/security/SecurityConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/SocialType.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/dto/MemberInfoResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/dto/MemberLoginRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/google/GoogleSocialService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/service/SocialService.java
  src/main/java/org/sopt/seonyakServer/global/exception/model/CustomException.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#17 [HOTFIX] #16 - CORS 설정파일 변경
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
Labels: 🧩 CHORE, 🔥 !HOTFIX, 🐯 석범

#21 [Feat]#15 - 구글 미트 API 연동
  .github/workflows/DOCKER-CD.yml
  .gitignore
  build.gradle
  src/main/java/org/sopt/seonyakServer/domain/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/global/auth/security/SecurityConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/service/GoogleSocialService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetController.java
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/dto/GoogleMeetUrlResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/OcrController.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/OcrService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/dto/OcrUnivResponse.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🛠️ FIX, 📂 FILE, 🐯 석범

#27 [FIX] #26 - JSON 라이브러리 적용
  .github/workflows/DOCKER-CD.yml
Labels: 🛠️ FIX, 🐯 석범

#29 [FIX] #28 - JSON 파일 경로 수정
  .github/workflows/DOCKER-CD.yml
Labels: 🛠️ FIX, 🐯 석범

#31 [FEAT] #30 - S3로부터 구글 설정파일 생성
  .github/workflows/DOCKER-CD.yml
Labels: ✨ FEAT, 🐯 석범

#33 [FIX] #32 - 리소스 디렉토리 생성 명령어 추가
  .github/workflows/DOCKER-CD.yml
Labels: 🛠️ FIX, 🐯 석범

#38 [FIX] #37 - JSON 파일 참조 절대경로로 수정
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
Labels: 🛠️ FIX, 🐯 석범

#42 [FIX] #41 - 구글 유저 생성 시 설정파일 경로 로깅
  .github/workflows/DOCKER-CD.yml
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
Labels: 🛠️ FIX, 🐯 석범

#44 [FIX] #43 - JSON 파일 ClassPathResource 객체로 열기
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
Labels: 🛠️ FIX, 🐯 석범

#46 [FEAT] #45 - JSON 폴더 생성
  .github/workflows/DOCKER-CD.yml
Labels: ✨ FEAT, 🐯 석범

#48 [FEAT] #47 - 구글 설정 JSON 로깅 추가
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐯 석범

#50 [FEAT] #49 - 구글 토큰 로깅 추가
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
Labels: ✨ FEAT, 🐯 석범

#52 [DEL] #51 - 구글 미트 설정 로깅 삭제
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
Labels: ⚰️ DEL, 🐯 석범

#54 [FEAT] #53 - 구글 토큰 S3로 관리
  build.gradle
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
Labels: ✨ FEAT, 🐯 석범

#34 [FEAT] #20 - 도메인 엔티티 작성
  src/main/java/org/sopt/seonyakServer/domain/appointment/controller/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/AppointmentStatus.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/repository/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberManagementService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/controller/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/senior/repository/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/senior/service/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/controller/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/dto/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/model/Department.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/University.java
  src/main/java/org/sopt/seonyakServer/domain/university/repository/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/service/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/util/JsonConverter.java
  src/main/java/org/sopt/seonyakServer/global/auth/filter/JwtAuthenticationFilter.java
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#60 [FIX] #58 - 도메인 엔티티 작성 코드 리뷰 반영
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberManagementService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/Department.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/University.java
  src/main/java/org/sopt/seonyakServer/domain/util/JsonConverter.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: 🛠️ FIX, 🐈‍⬛ 창균

#56 [FEAT] #55 - 네이버 명함 OCR API 연동
  src/main/java/org/sopt/seonyakServer/global/auth/security/SecurityConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/OcrConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/OcrController.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/OcrService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/naver/dto/OcrBusinessResponse.java
Labels: ✨ FEAT, 🧩 CHORE, ♻️ REFACTOR, 🐯 석범

#63 [FEAT] #59 - 사진 업로드를 위한 Presigned URL 구현
  build.gradle
  src/main/java/org/sopt/seonyakServer/global/common/external/googlemeet/GoogleMeetConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Controller.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Service.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/dto/PreSignedUrlResponse.java
  src/main/java/org/sopt/seonyakServer/global/config/S3Config.java
  src/test/java/org/sopt/seonyakServer/global/common/external/s3/S3ServiceIntegrationTest.java
Labels: ✨ FEAT, 🛠️ FIX, ♻️ REFACTOR, 🐯 석범

#62 [FEAT] #61 - 온보딩 닉네임 유효성 검증 API 구현
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/NicknameRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#65 [FEAT] #64 - BaseTimeEntity + 학교 이메일 인증 API 연동
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/Department.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/University.java
  src/main/java/org/sopt/seonyakServer/global/auth/security/SecurityConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/google/GoogleAccessTokenClient.java
  src/main/java/org/sopt/seonyakServer/global/common/external/client/google/GoogleUserClient.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertConfig.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertController.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertClientRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertResponse.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertVerifyClientRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/dto/UnivCertVerifyRequest.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/FeignErrorDecoder.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/UnivCertClient.java
  src/main/java/org/sopt/seonyakServer/global/common/model/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/common/model/BaseTimeEntity.java
  src/main/java/org/sopt/seonyakServer/global/config/FeignConfig.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🧩 CHORE, 🐯 석범

#67 [FEAT] #66 - 휴대전화 번호 인증 API 구현
  build.gradle
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/NicknameRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/SendCodeRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/VerifyCodeRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MessageService.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/config/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/config/RedisConfig.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/domain/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/domain/Code.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/repository/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/repository/CodeRepository.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/service/.gitkeep
  src/main/java/org/sopt/seonyakServer/global/auth/redis/service/CodeService.java
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#74 [HOTFIX/#73] 공통 에러타입 정리
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/UnivCertController.java
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/FeignErrorDecoder.java
Labels: 🔥 !HOTFIX, 🐈‍⬛ 창균, 🐯 석범

#75 [FEAT] #72 - 계열, 직무로 필터링하여 선배 조회 구현
  src/main/java/org/sopt/seonyakServer/domain/senior/controller/SeniorController.java
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/SeniorListResponse.java
  src/main/java/org/sopt/seonyakServer/domain/senior/repository/SeniorRepository.java
  src/main/java/org/sopt/seonyakServer/domain/senior/repository/SeniorRepositoryCustom.java
  src/main/java/org/sopt/seonyakServer/domain/senior/repository/SeniorRepositoryImpl.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
Labels: ✨ FEAT, 🐯 석범

#80 [FEAT] #79 - 약속 수락/거절 구현
  src/main/java/org/sopt/seonyakServer/domain/appointment/controller/AppointmentController.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentAcceptRequest.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentRejectRequest.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐯 석범

#81 [FEAT] #77 - 학교, 학과 검색 API 구현
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/SendCodeRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/VerifyCodeRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberManagementService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MessageService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/university/controller/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/controller/UnivController.java
  src/main/java/org/sopt/seonyakServer/domain/university/dto/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/dto/SearchDeptResponse.java
  src/main/java/org/sopt/seonyakServer/domain/university/dto/SearchUnivResponse.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/Department.java
  src/main/java/org/sopt/seonyakServer/domain/university/model/University.java
  src/main/java/org/sopt/seonyakServer/domain/university/repository/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/repository/DeptRepository.java
  src/main/java/org/sopt/seonyakServer/domain/university/repository/UnivRepository.java
  src/main/java/org/sopt/seonyakServer/domain/university/service/.gitkeep
  src/main/java/org/sopt/seonyakServer/domain/university/service/UnivService.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/domain/Code.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/service/CodeService.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#83 [FEAT] #82 - 회원가입 API 구현
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/MemberJoinRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/MemberJoinResponse.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#85 [FEAT] #84 - 구글 미트 회의실 링크 조회 API 구현
  src/main/java/org/sopt/seonyakServer/domain/appointment/controller/AppointmentController.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/GoogleMeetLinkResponse.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
  src/main/java/org/sopt/seonyakServer/global/auth/PrincipalHandler.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#87 [FEAT] #86 - 선배 상세 프로필 조회 API 구현
  src/main/java/org/sopt/seonyakServer/domain/senior/controller/SeniorController.java
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/SeniorProfileResponse.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#92 [Refactor] #91 - 문자 발송 서비스 리팩토링
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MessageService.java
  src/main/java/org/sopt/seonyakServer/global/exception/GlobalExceptionHandler.java
Labels: ✨ FEAT, 🛠️ FIX, 📂 FILE, ♻️ REFACTOR, 🐯 석범

#94 [FEAT] #93 - 선배 카드 정보 조회 구현
  src/main/java/org/sopt/seonyakServer/domain/member/dto/MemberJoinResponse.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/controller/SeniorController.java
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/SeniorCardProfileResponse.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
Labels: ✨ FEAT, 🐯 석범

#98 [FEAT] #90 - 나의 약속 조회 API 구현
  src/main/java/org/sopt/seonyakServer/domain/appointment/controller/AppointmentController.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentAcceptRequest.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentDetailResponse.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentRequest.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentResponse.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/AppointmentCard.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/AppointmentCardList.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/AppointmentStatus.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/DateTimeRange.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/repository/AppointmentRepository.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/PreferredTimeList.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/TimeRange.java
Labels: ✨ FEAT, ♻️ REFACTOR, 🐈‍⬛ 창균

#102 [FEAT] #101 - 약속 수락/거절 시 문자 발송 구현 및 오류 해결
  src/main/java/org/sopt/seonyakServer/domain/appointment/controller/AppointmentController.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentAcceptRequest.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/dto/AppointmentRejectRequest.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🛠️ FIX, 🐈‍⬛ 창균

#104 [FIX] #103 - 웹 설정파일 서버 도메인 추가
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
Labels: 🛠️ FIX, 🐯 석범

#106 [FIX] #105 - 선배 필터링 응답 명세대로 수정
  src/main/java/org/sopt/seonyakServer/domain/senior/controller/SeniorController.java
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/SeniorListResponseWrapper.java
Labels: 🛠️ FIX, 🐯 석범

#108 [FIX] #107 - 선배 필터링 응답 이미지 필드 추가
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/SeniorListResponse.java
  src/main/java/org/sopt/seonyakServer/domain/senior/repository/SeniorRepositoryImpl.java
Labels: 🛠️ FIX, 🐯 석범

#112 [FIX/#111] 약속 수락 API CORS 에러 해결
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
Labels: 🛠️ FIX, 🐈‍⬛ 창균

#114 [FEAT] #113 - 중복된 학과 이름 학과 리스트에 저장하지 않는 기능 추가
  src/main/java/org/sopt/seonyakServer/domain/university/service/UnivService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#116 [FEAT] #115 - 온보딩 시 이탈한 회원 DB를 삭제하는 스케줄링 로직 구현
  src/main/java/org/sopt/seonyakServer/SeonyakServerApplication.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/service/CodeService.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#119 [FIX] #117 - 입장한 약속 지난 약속으로 변경
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
Labels: 🛠️ FIX, 🐯 석범

#122 [FEAT] #121 - 소셜 로그인 시 분기 처리용 로직 구현
  src/main/java/org/sopt/seonyakServer/domain/member/dto/LoginSuccessResponse.java
  src/main/java/org/sopt/seonyakServer/domain/member/repository/MemberRepository.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
Labels: ✨ FEAT, 🛠️ FIX, 🐈‍⬛ 창균

#123 [FEAT] 사진 업로드 용 API 구현
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/dto/SeniorCardProfileResponse.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Controller.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Service.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🛠️ FIX, 🐯 석범

#127 [HOTFIX/#126] 회원가입 API 403 에러 해결
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
Labels: 🔥 !HOTFIX, 🐈‍⬛ 창균

#129 [HOTFIX] #128 - 소셜 로그인 응답 에러 및 회원가입 403 에러 해결
  src/main/java/org/sopt/seonyakServer/domain/member/controller/MemberController.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/MemberJoinRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
Labels: 🔥 !HOTFIX, 🐈‍⬛ 창균

#137 [FIX] #136 - 도메인 수정사항 CORS 설정파일에 반영
  src/main/java/org/sopt/seonyakServer/global/config/WebConfig.java
Labels: 🛠️ FIX, 🐈‍⬛ 창균

#141 [FIX] #140 - FeignErrorDecoder 로깅 추가
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/FeignErrorDecoder.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: 🛠️ FIX, ♻️ REFACTOR, 🐈‍⬛ 창균

#139 [FEAT] #138 - 약속 신청 시에도 알림 문자 발송하도록 추가
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
Labels: ✨ FEAT, 🛠️ FIX, 🐈‍⬛ 창균

#143 [FEAT] #142 - FeignErrorDecoder에 구글 소셜 로그인 Exception 분기 추가
  src/main/java/org/sopt/seonyakServer/global/common/external/univcert/feign/FeignErrorDecoder.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: ✨ FEAT, 🐈‍⬛ 창균

#145 [FIX] #144 - 간헐적 트랜잭션 오류 해결을 위한 객체 생성 로직 변경
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/Appointment.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/AppointmentCard.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/JuniorInfo.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/model/SeniorInfo.java
  src/main/java/org/sopt/seonyakServer/domain/appointment/service/AppointmentService.java
  src/main/java/org/sopt/seonyakServer/domain/member/dto/MemberJoinRequest.java
  src/main/java/org/sopt/seonyakServer/domain/member/model/Member.java
  src/main/java/org/sopt/seonyakServer/domain/member/service/MemberService.java
  src/main/java/org/sopt/seonyakServer/domain/senior/model/Senior.java
  src/main/java/org/sopt/seonyakServer/domain/senior/service/SeniorService.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/domain/Code.java
  src/main/java/org/sopt/seonyakServer/global/auth/redis/service/CodeService.java
  src/main/java/org/sopt/seonyakServer/global/common/external/s3/S3Service.java
  src/main/java/org/sopt/seonyakServer/global/exception/enums/ErrorType.java
Labels: 🛠️ FIX, ✏️ CORRECT, 🐈‍⬛ 창균
